Update globalsearch.php
davidbarratt/tools-standalone pull request #2
Opened 2019-06-23 20:18 UTC by zoranzoki21

Removed font-size element so title of each namespace can be viewed better.

See pictures (before) https://prnt.sc/o5ow9y (and after fix) https://prnt.sc/o5ow1c

2019-06-23 20:22 UTC, zoranzoki21 commented
@samwilson Can you merge this please?

2019-06-23 22:06 UTC, samwilson requested changes
Note that I'm not a maintainer of this repo. Happy to help review though.

2019-06-23 22:06 UTC, samwilson commented on globalsearch.php
> -						<tr style='font-size:0.5em;'>
Only the `style` attribute should be removed, not the whole element. The `<tr>` is part of the table structure.

2019-06-24 00:39 UTC, samwilson approved these changes
Looks good. @davidbarratt are you a maintainer here?

2019-06-24 13:11 UTC, kizule commented on globalsearch.php
> -						<tr style='font-size:0.5em;'>
Should be ok now, check it please.

2019-06-24 16:01 UTC, merged